<a href="https://colab.research.google.com/github/Aniket4095/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr_str = ['BMW','Audi','Jaguar','Hyundai']
arr_num = [4,5,2,3,5]

np_str = np.array(arr_str)
np_num = np.array(arr_num)

print("Numpy array as a string ",np_str)
print("Numpy array containing numbers",np_num)

Numpy array as a string  ['BMW' 'Audi' 'Jaguar' 'Hyundai']
Numpy array containing numbers [4 5 2 3 5]


In [3]:
type(np_str)

numpy.ndarray

In [4]:
type(arr_str)

list

In [6]:
matrix = np.array([[1,2,3],[1,2,1],[4,5,3]])
print(matrix)

[[1 2 3]
 [1 2 1]
 [4 5 3]]


In [7]:
arr = np.arange(0,10)

In [9]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr_1 = np.arange(1,10,3)

In [11]:
print(arr_1)

[1 4 7]


In [14]:
matrix1 = np.linspace(1,20,5)
print(matrix1)

[ 1.    5.75 10.5  15.25 20.  ]


In [16]:
matrix2 = np.zeros([3,5],dtype = int )
print(matrix2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [18]:
matrix3 = np.eye(2)
print(matrix3)

[[1. 0.]
 [0. 1.]]


In [22]:
arr_re = np.arange(0,8).reshape((2,4))

In [23]:
print(arr_re)

[[0 1 2 3]
 [4 5 6 7]]


In [26]:
matrix1= np.arange(1,10).reshape((3,3))

matrix2 = np.arange(11,20).reshape(3,3)

print(matrix1,matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [27]:
np.min(matrix1)

1

In [28]:
np.max(matrix1)

9

In [29]:
rand_mat = np.random.rand(5)
print(rand_mat)

[0.79543193 0.94210647 0.94088518 0.81224592 0.36829153]


In [30]:
rand_mat1 = np.random.rand(3,3)
print(rand_mat1)

[[0.72649989 0.11202286 0.81112534]
 [0.99593304 0.70600665 0.76202533]
 [0.80552194 0.55867035 0.42814843]]


In [32]:
rand_mat2 = np.random.randint(1,5,10)

In [33]:
print(rand_mat2)

[3 4 3 4 2 4 2 2 4 3]


In [34]:
rand_mat3 = np.random.randint(1,10,[5,5])

In [35]:
print(rand_mat3)

[[7 2 9 9 5]
 [4 6 2 4 7]
 [6 3 7 6 3]
 [5 7 5 7 3]
 [8 8 4 7 9]]


In [36]:
rand_arr = np.random.randn(10)
print(rand_arr)

[-0.24395003 -0.56356679  0.43646206 -0.04609679 -0.94513771 -1.18472177
 -0.15189687 -1.12724997  0.17486196  1.98652712]


In [37]:
rand_arr > 0

array([False, False,  True, False, False, False, False, False,  True,
        True])

In [39]:
print(rand_arr[rand_arr>0])

[0.43646206 0.17486196 1.98652712]


In [40]:
rand_mat = np.random.randn(5,5)

In [41]:
print(rand_mat)

[[-1.17038545 -0.39182709  0.19685992 -1.63811313  1.23383292]
 [-0.42254535  0.80493507  0.43130728  0.05811542  0.13690964]
 [ 1.24555182  0.55437855 -0.10969275 -0.30271637  0.47706332]
 [ 0.30326137 -0.10981169  0.92567868 -0.30085579 -0.49739501]
 [-1.19017938  0.70203095  2.41662891 -0.06910278  1.3652942 ]]


In [42]:
rand_mat[1]

array([-0.42254535,  0.80493507,  0.43130728,  0.05811542,  0.13690964])

In [43]:
rand_mat[2][3]

-0.3027163705408789

In [45]:
rand_mat[0:3,2:4]

array([[ 0.19685992, -1.63811313],
       [ 0.43130728,  0.05811542],
       [-0.10969275, -0.30271637]])